language: node_js

node_js:
  "stable"
  
cache:
  directories: 
    "node_modules"

script:
  - npm run test

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE pg-node-travis-test;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD 'Svu5ncka';" -U postgres